# on:
#   push:
#     branches:
#       - master



# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: "Login to Docker hub"
#         run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}} 

#       - name: "Bulding docker image"
#           run: docker build -t ${{secrets.DOCKER_USERNAME}}/images .

#       - name: "pushing to Docker hub"
#             run: docker push  ${{secrets.DOCKER_USERNAME}}/images 
    
name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/images .

      - name: Push to Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/images



